Setup CI (#2)
* wip

* Author

* Comments Form

* update env and readme

* comments section

* Carousel

* Category Page

* fallback for slug post pages

* size workflow & ci

* jest setup

* Icon Tests

* add test checks and pre-push check & build step

* add test-coverage action

* lint alias

* coverage action

* ci

* typo

* custom coverage workflow

* typo

* Refactor action workflow

* Rename workflow

* Add Coverage Badge

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -14,9 +14,9 @@ yarn check-format ||
 # Check ESLint Standards
 yarn check-lint ||
 (
-        echo '😤🏀👋😤 Please fix voltatile code ! 😤🏀👋😤 
+        echo '😤🏀👋😤 Please fix voltatile code ! 😤🏀👋😤
                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-        false; 
+        false;
 )
 
 # Check tsconfig standards
@@ -38,12 +38,11 @@ yarn lint-staged || (
     return false;
 )
 
-yarn build ||
-(
-    echo '❌👷🔨❌ Better call Pan... Because your build failed ❌👷🔨❌
-            Next build failed: View the errors above to see why. 
-    '
-    false;
+#Run Tests 
+yarn test || (
+        
+        echo 'Something went wrong ... Tests Failed. Please fix the above errors !'
+        return false;
 )
 
 # If everything passes... Now we can commit
